### ISSUE TITLE
RESET PASSWORD: Missing space

### ISSUE THREAD

**Issue by johanlundberg** [SUNET/eduid-front#1032]
#### Description of issue:
Missing space before link.
---

![image](https://user-images.githubusercontent.com/105702/166649041-1676fe43-3192-492e-8d7f-07ca3bc4d76f.png)

---

**Comment by eunjuhuss** [comment]
<img width="702" alt="Screenshot 2022-05-06 at 11 02 32" src="https://user-images.githubusercontent.com/44289056/167101428-e11d8bde-e010-4566-83a0-1b2d57c2b4fb.png">
