### ISSUE TITLE
GENERAL: What are these files?

### ISSUE THREAD

**Issue by njons** [SUNET/eduid-front#106]
What do these files do? Are they rendered in the current version (in staging) of the app?

- components/OpenidConnect.js
- components/OpenidConnectFreja.js
- components/PendingActions.js

**Comment by enriquepablo** [comment]
components/PendingActions.js

This was a clickable reminder of the actions that the user had to perform to complete the profile:

![2019-11-25-102457_1200x390_scrot](https://user-images.githubusercontent.com/284715/69529552-65f82c80-0f68-11ea-9e46-4a0b2a60d04f.png)

**Comment by enriquepablo** [comment]
components/OpenidConnect.js
components/OpenidConnectFreja.js

This stuff was developed by Johan, he'll be able to explain it better than me

**Comment by njons** [comment]
If components/PendingActions.js is a reminder from the old version I will suggest we remove it.

**Comment by johanlundberg** [comment]
components/OpenidConnect.js
This is the se-leg vetting button.

components/OpenidConnectFreja.js
This was the Freja eID vetting button before we changed method for doing Freja eID. I guess it can be removed.
