### ISSUE TITLE
GENERAL: Structure of folders (img)

### ISSUE THREAD

**Issue by njons** [SUNET/eduid-front#110]
Can we put the img folder inside the public folder?

**Comment by enriquepablo** [comment]
I don't see why not. However, as far as I know the public folder is not being used at the moment, since we started serving the index and bundles from the jsconfig app.

**Comment by njons** [comment]
@enriquepablo  Yeah it would totally be from the convention to keep static files in the public folder. My aim was to just add some structure to the folders.
