### ISSUE TITLE
DASHBOARD: More info about DashboardMain props

### ISSUE THREAD

**Issue by njons** [SUNET/eduid-front#111]
_components/DashboardMain.js_

- What is prop ‘staticContext’?
- What is prop ‘is_configured’?
- What is prop ‘is_spa’?

**Comment by enriquepablo** [comment]
> What is prop ‘staticContext’?
No idea, where did you see it?

> What is prop ‘is_configured’?
When the dashboard initializes, it asks the server for some configuration parameters, and when it receives them successfully (i.e., an GET_JSCONFIG_CONFIG_SUCCESS action is dispatched) it turns the "is_configured" flag in the state from false to true. This is then propagated to the props of certain components that act accordingly.

> What is prop ‘is_spa’?
This is a relic, no longer used, from a time when it was thought that perhaps some components might be used outside a SPA.
