### ISSUE TITLE
DASHBOARD: Naming standard for actions

### ISSUE THREAD

**Issue by njons** [SUNET/eduid-front#113]
_actions/DashboardConfig.js_

Do we have a naming convention for all actions (if so please let me know!)? If not, can we set one? 

> I, personally, like when the actions have a GET or POST and if the name givs a hint of what will be returned from the store when the action is triggered. What do you think?

In light of the above:
- Can we rename ‘GET_JSCONFIG_CONFIG’ to ‘GET_DASHBOARD_CONFIG?’
- Should the naming of ‘SPIN’ be something like ‘GET_SPINNER_STATUS’?

**Comment by enriquepablo** [comment]
Action types that trigger a request to some service, or are included in some response from the server, do follow a convention, [dictated by some server side names](https://github.com/SUNET/eduid-common/blob/master/src/eduid_common/api/utils.py#L127), so they cannot be modified. Of course we can modify the names of the variables that hold them, but that tends to be extremely confusing.

Names for the types of the actions that have no async effects follow no convention, so they can be modified without problem.

**Comment by enriquepablo** [comment]
Action types that are involved in async effects tend to have names that start with POST_ or GET_

**Comment by johanlundberg** [comment]
The response from the backend will contain the GET_JSCONFIG_CONFIG as it was a GET request that was answered from a view in the blueprint jsconfig with the path config. We could split the endpoint in two blueprints named dashboard and signup ofc.
