### ISSUE TITLE
DASHBOARD: Add APP_LOADED logic?

### ISSUE THREAD

**Issue by njons** [SUNET/eduid-front#114]
_actions/DashboardConfig.js_

- Can we add ‘APP_LOADING/APP_LOADED’ logic to Dashboard?
- What does ‘SPIN’ do? Does it come with the ‘APP_LOADING/APP_LOADED’ logic?

**Comment by enriquepablo** [comment]
> _actions/DashboardConfig.js_
> 
>     * Can we add ‘APP_LOADING/APP_LOADED’ logic to Dashboard?

Sure, I'll add it to my queue

> 
>     * What does ‘SPIN’ do? Does it come with the ‘APP_LOADING/APP_LOADED’ logic?

It seems it is a relic of the past and can be removed, enqueuing the task
