### ISSUE TITLE
DASHBOARD: Understanding the fetching functionality in the reducer

### ISSUE THREAD

**Issue by njons** [SUNET/eduid-front#115]
_reducers/DashboardConfig.js_

Are the fetching actions in the reducer related to the fetching context that disables buttons or is it more crucial to the actual startup of the app? 

- Is ‘const fetchingActions/unFetchingActions’ related to the FetchingContext component or actually fetching what is needed to load the app?

**Comment by enriquepablo** [comment]
> _reducers/DashboardConfig.js_
> 
> Are the fetching actions in the reducer related to the fetching context that disables buttons or is it more crucial to the actual startup of the app?
> 
>     * Is ‘const fetchingActions/unFetchingActions’ related to the FetchingContext component or actually fetching what is needed to load the app?

Both things are related to the fetching context.

**Comment by enriquepablo** [comment]
What should be refactored here?
