### ISSUE TITLE
DASHBOARD: Removing 'show_sidebar' prop functionality

### ISSUE THREAD

**Issue by njons** [SUNET/eduid-front#116]
_reducers/DashboardConfig.js_

I have removed the prop show_sidebar because thats no longer what the website displays. Do we need the ‘show_sidebar: true/false’ functionality in the reducer?

**Comment by enriquepablo** [comment]
> _reducers/DashboardConfig.js_
> 
> I have removed the prop show_sidebar because thats no longer what the website displays. Do we need the ‘show_sidebar: true/false’ functionality in the reducer?

No, it can be removed
