### ISSUE TITLE
REGISTER: Naming standard for actions?

### ISSUE THREAD

**Issue by njons** [SUNET/eduid-front#118]
_actions/SignupMain.js_

As in PR #113, If there is no naming standard for actions I would suggest we set one.  

In light of that: 
- Can ‘GET_CODE_STATUS’ be renamed to something more specific (like ‘GET_EMAIL_LINK_STATUS’...or something more appropriate)
- Should the naming of ‘APP_LOADING/APP_LOADED’ be something like ‘GET_APP_STATUS_FAIL/GET_APP_STATUS’?

**Comment by enriquepablo** [comment]
> _actions/SignupMain.js_
> 
> As in PR #113, If there is no naming standard for actions I would suggest we set one.

Answered in the referenced ticket

> 
> In light of that:
> 
>     * Can ‘GET_CODE_STATUS’ be renamed to something more specific (like ‘GET_EMAIL_LINK_STATUS’...or something more appropriate)
> 
>     * Should the naming of ‘APP_LOADING/APP_LOADED’ be something like ‘GET_APP_STATUS_FAIL/GET_APP_STATUS’?

I think that 'APP_LOADING/APP_LOADED’ reflects better what is happening (loading stuff from the server and rendering it while we show a spinning wheel) than ‘GET_APP_STATUS_FAIL/GET_APP_STATUS'
