### ISSUE TITLE
REGISTER: removing empty unFetchingActions variable?

### ISSUE THREAD

**Issue by njons** [SUNET/eduid-front#119]
_reducers/SignupMain.js_

- Is it possible to remove the ‘unFetchingActions’ variable or does it need to be defined as an empty array?

**Comment by enriquepablo** [comment]
It's there in all "config" reducers, to make it easier to add actions that take the app out of the "is fetching" state. In principle, all actions whose type ends in "_FAIL" or "_SUCCESS" will do that (take the app out of the fetching state) but we might need to add more.

**Comment by enriquepablo** [comment]
To remove it, it would need to be removed from further down in the reducer file, where it is used - but then if it is ever needed it will be harder to reinstate.
