### ISSUE TITLE
PLUGINS: Component file includes both component and container code

### ISSUE THREAD

**Issue by njons** [SUNET/eduid-front#122]
_plugins/eduid_action.mfa/component,
plugins/eduid_action.tou/component_

- Why do component.js hold both component and container code? (I am curious because this deviates from the folder structure of the other components)

**Comment by enriquepablo** [comment]
No reason, just experimenting a bit to see what structure is more comfortable to work with - I had the impression that I was all the time going back and forth between containers and components.
