### ISSUE TITLE
PLUGINS: Are the 'init-config' the same?

### ISSUE THREAD

**Issue by njons** [SUNET/eduid-front#124]
_plugins/eduid_action.mfa/init-config.js_
_plugins/eduid_action.tou/init-config.js_

- Are the two ‘init-config.js’ files the same? 
- can tehy be refactored to reduce the number of files?

**Comment by enriquepablo** [comment]
see https://github.com/SUNET/eduid-front/issues/123

Also, in this case the intent of those files is to add specific configuration to each plugin, so they might end up differing.
