### ISSUE TITLE
PLUGINS: Are the store.js files the same?

### ISSUE THREAD

**Issue by njons** [SUNET/eduid-front#126]
_plugin-skel/store.js_
_plugins/eduid_action.mfa/store.js_
_plugins/eduid_action.tou/store.js_

- The three store files look like they are importing the same things. 
- Can they be refactored to reduce the number of files?

**Comment by enriquepablo** [comment]
> _plugin-skel/store.js_

This is template code, to be copied to any new plugin as basic boilerplate.

> _plugins/eduid_action.mfa/store.js_
> _plugins/eduid_action.tou/store.js_

And these are the specific stores for each plugin.

> 
>     * The three store files look like they are importing the same things.

They need to import the same things to build a redux store - but each plugin builds a different store.

> 
>     * Can they be refactored to reduce the number of files?

What are you thinking about as refactorization?
