### ISSUE TITLE
PLUGINS: Structure of folders (style)

### ISSUE THREAD

**Issue by njons** [SUNET/eduid-front#127]
_plugin-skel/style.scss_
 _plugins/eduid_action.mfa/style.scss_
 _plugins/eduid_action.tou/style.scss_

- Can the style files be combined?
- Why are the style files not in the src/style/ folder?

**Comment by enriquepablo** [comment]
> _plugin-skel/style.scss_
> _plugins/eduid_action.mfa/style.scss_
> _plugins/eduid_action.tou/style.scss_
> 
>     * Can the style files be combined?

They might be combined, but then you would be pulling all styles needed for the MFA plugin app into the ToU plugin app, and viceversa, right? Or do you mean something else?

> 
>     * Why are the style files not in the src/style/ folder?

All the files that are specific to each plugin app reside in a common folder. It makes the development of each plugin less hard.
