### ISSUE TITLE
GENERAL: Structure (initialisation) code in the order it is executed

### ISSUE THREAD

**Issue by njons** [SUNET/eduid-front#129]
Organise the  initialisation action code in the order it is executed. 

- Dashboard
- Signup
- Login

> I see no problem reordering the actions and reducers. There is initialization code, and then there is code that is executed whenever the user chooses...
_Originally posted by @enriquepablo in https://github.com/SUNET/eduid-front/issues/107#issuecomment-558083279_

**Comment by enriquepablo** [comment]
To do this we better wait for the pending PRs to be merged, otherwise we'll have plenty of conflicts

**Comment by enriquepablo** [comment]
PR for this:

https://github.com/SUNET/eduid-front/pull/158
