### ISSUE TITLE
Remove OpenidConnectFreja.js

### ISSUE THREAD

**Issue by njons** [SUNET/eduid-front#142]
>components/OpenidConnectFreja.js
This was the Freja eID vetting button before we changed method for doing Freja eID. I guess it can be removed.
_Originally posted by @johanlundberg in https://github.com/SUNET/eduid-front/issues/106#issuecomment-558238390_

**Comment by johanlundberg** [comment]
I guess we still need OpenidConnect.js to do se-leg vettings?

**Comment by njons** [comment]
Changed to only remove OpenidConnectFreja.js
