### ISSUE TITLE
SIGNUP: button not navigating to Profile after completing signup

### ISSUE THREAD

**Issue by njons** [SUNET/eduid-front#155]
<img width="259" alt="Screenshot 2019-11-29 at 13 54 32" src="https://user-images.githubusercontent.com/30963614/69870740-28213e00-12b1-11ea-83f0-f394ec3ce74a.png">

**Comment by eunjuhuss** [comment]
**potential fix** 
- Change button text to inform user where they will navigate.
- Add explanatory text to inform user that they need to save password before click the button.
