### ISSUE TITLE
VETTING: Pattern to trigger modals

### ISSUE THREAD

**Issue by njons** [SUNET/eduid-front#161]
(found in code comments)
**In letter proofing**: a get request checks what has been stored in db and generates the modal
**In mobile proofing**: currently has separate action to show/hide modal, but could change confirmingMobile from true to false to generate the modal (GET_MOBILE_PROOFING_PROOFING)

**Comment by njons** [comment]
I vote that the **modal be triggered by a separate/dedicated action** so that it can be identified in the code. 

> Even better would be to be able to let multiple DOM elements tap into the SHOW/HIDE action. And to set this a a standard for all common actions.

Any objections let me know...

**Comment by enriquepablo** [comment]
If I understand correctly, a single action for all modals would prevent us from having more than one modal per rendered page. And we have components that have more than one modal, e.g.:

https://github.com/SUNET/eduid-front/blob/master/src/components/Security.js
https://github.com/SUNET/eduid-front/blob/master/src/components/LetterProofing.js
