### ISSUE TITLE
GENERAL: English and Swedish mixed on Login page, Too many requests page and New Password

### ISSUE THREAD

**Issue by ovesemart** [SUNET/eduid-front#245]
Some labels on the login page & too many requests page are written in English and others in Swedish. Or to be more specific. 
two labels in English, rest in Swedish. This is also seen on page when a new account has been registered and confirmed. 
Update: Also found this problem on New Password page (headings for tabs are in English, rest in swedish.

<img width="1193" alt="Skärmavbild 2020-03-23 kl  17 49 50" src="https://user-images.githubusercontent.com/36661180/77341661-567acb80-6d2f-11ea-86ee-479cb8ca8006.png">

<img width="1196" alt="Skärmavbild 2020-03-24 kl  10 56 38" src="https://user-images.githubusercontent.com/36661180/77412560-54ac1900-6dbe-11ea-8d8a-9b3f32913a1e.png">

![TC_38-confirmedNewAccount](https://user-images.githubusercontent.com/36661180/95825876-d13e1f00-0d31-11eb-846a-b39dfb446169.png)

![TC_25-extraSecurity-1](https://user-images.githubusercontent.com/36661180/115741490-1baef100-a390-11eb-8e12-61f518ac57dd.png)
)

**Comment by njons** [comment]
- The mixed language on the login page is known and will be addressed by completion of the new login app. 
    - So adding this issue to the Login app project

- However, a further investigation into the error pages will be necessary as **I am not sure how they render** 
   -  if they are templates, they should probably also be changed into React to fully match the rest of the website
   - Should be added to its own project
