### ISSUE TITLE
TOU: Clicking on EduId Logo nothing happens

### ISSUE THREAD

**Issue by eunjuhuss** [SUNET/eduid-front#339]
#### Description of issue:
- There is no other option to click, user only can click "ACCEPT" button. 
and Nothing happens when clicking EduId Logo.

#### Potential fix: 
- Attach link to home

**Comment by njons** [comment]
Thank you for adding this issue!
 
Could we expand this issue to: making a list fo all pages* the logo is not working**? 

*all pages: home, login, reset password, register, dashboard, change password 
**working: redirecting to home...unless you're in the dashboard(?)
