### ISSUE TITLE
TOU LOGIN: Scrollbar on mobile

### ISSUE THREAD

**Issue by njons** [SUNET/eduid-front#346]
#### Description of issue:
Smallest width has a scrollbar at 320px (although other pages does not) 

* Browser: Safari
* Mobile model: iPhone SE

--- 
###### Reoccurring tou mobile (width: 320px)
<img width="1051" alt="Screenshot 2020-06-23 at 08 38 40" src="https://user-images.githubusercontent.com/30963614/85369312-307ee600-b52d-11ea-8ffc-af87f18ffc95.png">

--- 

#### Potential fix: 
- look into whether we need to apply a css fix to this
- See if fix for the other pages (e.g. register does not have it) can be used

**Comment by eunjuhuss** [comment]
looked into pages, I don't think it is a problem.
scrollbar appear at login, Tou and register pages when scrolling.

- Browser: Safari
- Mobile model: iPhone SE
- Page: Tou
<img width="677" alt="Screenshot 2020-06-23 at 10 17 47" src="https://user-images.githubusercontent.com/44289056/85379575-37612500-b53c-11ea-86e7-41e31d31ecba.png">

- Browser: Chrome
- Mobile model: iPhone SE
- Page: Tou

<img width="338" alt="Screenshot 2020-06-23 at 10 27 24" src="https://user-images.githubusercontent.com/44289056/85379593-3af4ac00-b53c-11ea-88c6-af7548ca1569.png">

- Browser: Chrome
- Mobile model: iPhone SE
- Page: Register

<img width="344" alt="Screenshot 2020-06-23 at 10 27 09" src="https://user-images.githubusercontent.com/44289056/85379601-3d570600-b53c-11ea-8b29-4c1aa430b849.png">
