### ISSUE TITLE
Minor lingual issues when confirming identity in Swedish

### ISSUE THREAD

**Issue by fredrikt** [SUNET/eduid-front#354]
#### Description of issue:

In Swedish, since it only concerns Swedish texts.

På sidan där man bekräftar sin identitet:

- [x] Det står "för de som har" på knapparna. Kanske borde stå "för dig som har"? Det är ju bara jag som är inloggad.
- [x] "Registret med telefonnummer uppdateras av mobiloperatörerna och har inget krav på att innehålla alla nummer." kanske borde vara "Registret med telefonnummer uppdateras av mobiloperatörerna och innehåller inte nödvändigtvis alla nummer."
- [x] Felstavat säkehetsskäl -> säkeRhetsskäl
- [x] Ta bort "så" ur "För att använda det här alternativet så måste du"

**Comment by eunjuhuss** [comment]
I would consider to keep the current use of "för de som har". I think that we should not limit us by focusing on individuals when designing the interface.
