### ISSUE TITLE
SETTINGS: Minor spelling issue in Change Password, in Swedish

### ISSUE THREAD

**Issue by ovesemart** [SUNET/eduid-front#447]
#### Description of issue:
The word: antingen is not correct spelled in change password sentence:
Du kan **antigen** använda ett rekommenderat lösenord som vi skapar åt dig eller ett du väljer helt själv.

<img width="893" alt="Skärmavbild 2020-09-24 kl  11 41 23" src="https://user-images.githubusercontent.com/36661180/94128846-eb838c00-fe5a-11ea-8ff9-fb7ef5d69b42.png">

**Comment by eunjuhuss** [comment]
Fixed https://github.com/SUNET/eduid-front/pull/451
