### ISSUE TITLE
SIGNUP: Mismatch in text and what the user is expected to do

### ISSUE THREAD

**Issue by johanlundberg** [SUNET/eduid-front#555]
#### Description of issue:
When a user signs up but does not complete the process (clicking the link in the mail) and tries to signup again the
text says that a new mail has been sent but the user actually has to press a button to send a new mail.

--- 

![image](https://user-images.githubusercontent.com/105702/114865775-07e51700-9df3-11eb-92ff-bc7363b6ef3e.png)

--- 

#### Potential fix: 
Instead of the text "A link has been sent to your email address." It should probably say "Do you want to send a new link to [email address]?"

**Comment by fredrikt** [comment]
Is the previous link still valid? If not, we ought to just send a new e-mail and not require user action.

**Comment by johanlundberg** [comment]
Agreed @fredrikt.

I created this PR https://github.com/SUNET/eduid-backend/pull/25 for that.
This means that the resend-functionality in frontend can be removed.
