### ISSUE TITLE
LOGIN: reset password link needs a second click

### ISSUE THREAD

**Issue by johanlundberg** [SUNET/eduid-front#662]
#### Description of issue:
The first click on the reset password link results in the email address text field showing an error saying "Field cannot be empty".

--- 

![image](https://user-images.githubusercontent.com/105702/129874130-1ed7e540-524b-46b4-a059-8119aa7418fc.png)

**Comment by eunjuhuss** [comment]
https://github.com/SUNET/eduid-front/pull/669
