### ISSUE TITLE
PASSWORD RESET: Validation of otp code is not done at submitting the code

### ISSUE THREAD

**Issue by ovesemart** [SUNET/eduid-front#703]
#### Description of issue:
The OTP is not validated when pressing save, user is sent to the next page and after the validation of new password is done, then the user will be notified that the otp was not correct. I think it should be done directly at pressing save.

--- 

<img width="1292" alt="Skärmavbild 2021-09-14 kl  13 38 59" src="https://user-images.githubusercontent.com/36661180/133251259-725b2405-ecc5-44eb-9d80-39fc239ebc5b.png">
<img width="1069" alt="Skärmavbild 2021-09-14 kl  13 46 50" src="https://user-images.githubusercontent.com/36661180/133252090-7b6b831f-2c00-41a3-aaf0-7b6b8b67ed14.png">

**Comment by eunjuhuss** [comment]
This is due to a backend limitation that sends all the information in one go, 
We have to solve this in cooperation with backend for the next version of reset password
