### ISSUE TITLE
PASSWORD RESET: Timer between sending the OTP to phone

### ISSUE THREAD

**Issue by ovesemart** [SUNET/eduid-front#723]
#### Description of issue:
Status message says that we can only send every 5min. Testing after 10mins gives same response i.e. the limit is at least 10min and either the Status message or configured time should be updated.
--- 

<img width="943" alt="Skärmavbild 2021-09-21 kl  07 24 44" src="https://user-images.githubusercontent.com/36661180/134116232-a42b175f-44a6-4916-8d2d-658eb57e4448.png">

**Comment by johanlundberg** [comment]
The default is 300 seconds, I just tried it with 10 seconds and that seems to work as intended.
