### ISSUE TITLE
IDENTITY: Avoid line break in date

### ISSUE THREAD

**Issue by ovesemart** [SUNET/eduid-front#761]
#### Description of issue:
At least at confirm ID by Letter, we have a line break in the date. If possible, it would be great to keep the date at one line.

--- 
<img width="776" alt="Skärmavbild 2021-10-21 kl  17 06 07" src="https://user-images.githubusercontent.com/36661180/138314434-edc24369-e750-4a5f-b26b-5f495947ae2b.png">

**Comment by johanlundberg** [comment]
fixed by #763
